// init/known/index.ts
export { hilbert }      from "./hilbert";
export { pascal }       from "./pascal";
export { magic }        from "./magic";
export { circul }       from "./circul";
export { lehmer }       from "./lehmer";
export { minij }        from "./minij";
export { tridiag }      from "./tridiag";
export { cauchy }       from "./cauchy";
export { frank }        from "./frank";
export { grcar }        from "./grcar";
export { kahan }        from "./kahan";
export { invhess }      from "./invhess";
export { binomial }     from "./binomial";
export { wathen }       from "./wathen";
export { neumann }      from "./neumann";
export { dorr }         from "./dorr";
export { house }        from "./house";
export { orthog }       from "./orthog";
export { randsvd }      from "./randsvd";
export { fiedler }      from "./fiedler";
export { hanowa }       from "./hanowa";
export { smoke, smokeComplex } from "./smoke";
export { wilkinson }    from "./wilkinson";
